### ISSUE TITLE
Fragment matching warnings and errors due to missing __typename

### ISSUE THREAD

**Issue by chuckbergeron** [DeltaCamp/apollo-link-ethereum#2]
Currently if you use Apollo fragments with this library you receive warnings and errors due to missing __typename definitions when writing to the cache.

With the heuristic fragment matcher:

<img width="1680" alt="screenshot 2019-01-24 15 27 59" src="https://user-images.githubusercontent.com/35717/51715234-bd4a0b00-1fec-11e9-8ddd-4e3f45d93a1a.png">

With the introspection fragment matcher and no types set (automatic inference):

<img width="1680" alt="screenshot 2019-01-24 15 25 41" src="https://user-images.githubusercontent.com/35717/51715233-bd4a0b00-1fec-11e9-97bf-94adbf747e2c.png">

Here's a basic config for the introspection fragment matcher:

```js
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: {
    __schema: {
      types: [] // no types provided
    }
  }
})

const cache = new InMemoryCache({
  fragmentMatcher,
  addTypename: false
})
```

**Comment by asselstine** [comment]
Fixed by type variables for most directives.
